### ISSUE TITLE
Rename isComplex to isComplexNumber

### ISSUE THREAD

**Issue by nicolas-cellier-aka-nice** [SergeStinckwich/SciSmalltalk#16]
I did it in http://www.squeaksource.com/Complex because:
- Pharo3.0 already has isComplex, and overrides are nasty
- isComplex is too much polymorphic (other things are complex in the image like parse nodes)

Name: Math-Complex-nice.3
-----
Ancestors: Math-Complex-nice.2

Rename isComplex to isComplexNumber
(to avoid nasty override in Pharo 1 & 2)

Name: Math-Complex-nice.4
-----
Ancestors: Math-Complex-nice.3

I lost Object extension #isComplexNumber in last commit, thanks to Pharo2.0 tools which incorreclty classify 'as yet unclassified' when changing code in a method list browser... 

Name: Math-Complex-nice.5
-----
Author: nice
Ancestors: Math-Complex-nice.4

Play it again, thanks for Pharo2.0 tools that did not reverse definition of isComplex when I asked to...

I never saw such an impractical browser for a long time @#*!
And thanks to Pharo2.0 MC UI to not present which method changed when I commit, which would have been too precious a feedback on bad bad browser behavior.
It's like one was willing to change all that did work so far for the sake of changing...
Correct this sacrilege.

**Comment by SergeStinckwich** [comment]
Apparently this is already commit in the last SciSmalltalk version
