### ISSUE TITLE
Simplify Quaternion reduce

### ISSUE THREAD

**Issue by nicolas-cellier-aka-nice** [SergeStinckwich/SciSmalltalk#18]
From http://www.squeaksource.com/Quaternion

Name: Math-Quaternion-nice.14
-----
Ancestors: Math-Quaternion-nice.13

Avoid invoking Number>>reduce, because Float does not preserve its (non) integrity.
Don't use unreal, to avoid an unecessary object creation.

**Comment by SergeStinckwich** [comment]
What is the status of this issue, Nicolas ?

**Comment by nicolas-cellier-aka-nice** [comment]
Closed because workaround have been introduced in Math-Quaternion-nice.7 (SmalltalkHub version).

**Comment by SergeStinckwich** [comment]
Great ! Thank you Nicolas
