### ISSUE TITLE
Implement a FFT and FTW

### ISSUE THREAD

**Issue by SergeStinckwich** [SergeStinckwich/SciSmalltalk#21]
Try to extract and run the FFT (Fast Fourier Transform) and FWT (Fast Wavelet Transform) classes from Squeak 4.5 image as a first draft.

http://magaloma.seasidehosting.st/Sound#FFT
http://magaloma.seasidehosting.st/Sound#FWT

**Comment by WernerK** [comment]
i translated squeaks fft. the fwt, yes, is just a fast wavelet transform and as a general wavelet package leaves something to be desired imo. hence i didnt touch it at the moment.
werner

**Comment by SergeStinckwich** [comment]
This issue was moved to PolyMathOrg/PolyMath#9
