### ISSUE TITLE
Shapiro-Wilk test

### ISSUE THREAD

**Issue by bergel** [SergeStinckwich/SciSmalltalk#23]
This is useful to check for data normality.
https://en.wikipedia.org/wiki/Shapiro%E2%80%93Wilk_test

**Comment by SergeStinckwich** [comment]
This issue was moved to PolyMathOrg/PolyMath#2

**Comment by SergeStinckwich** [comment]
This issue was moved to PolyMathOrg/PolyMath#3

**Comment by SergeStinckwich** [comment]
This issue was moved to PolyMathOrg/PolyMath#5
