### ISSUE TITLE
Add Line Search algorithm

### ISSUE THREAD

**Issue by mobius-eng** [SergeStinckwich/SciSmalltalk#27]
Line Search is used in Newton's method to prevent divergence if the initial point was chosen too far from actual root. Consider equation:

atan x = 0 (with solution x = 0)

If x0 is chosen too far away, for example, x0 = 2, Newton's method will diverge. as each approximation step will overshoot. Line search backtracks along the line of the step to reduce the step size.

Slice is available on SmalltalkHub: http://smalltalkhub.com/#!/~PolyMath/PolyMathInbox/versions/SLICE-Issue-27-Add-Line-Search-Algorithm-MobiusEng.1

**Comment by Ducasse** [comment]
I integrated it in 0.53 now I have no idea how to close a bug

**Comment by SergeStinckwich** [comment]
Click on close :-)
